### PR TITLE
Allow veryisolated networks

### PR DESCRIPTION
**Pull request by joejulian**
With veryisolated networks, there is no ip address assigned thus
matching the network name and ip address fails. This allows the null ip
address to match a named network when that forward_mode is set.

### CODE REVIEW

**Comment by pronix** [comment]
hello
I not use this type of network. can you show libvirt doc where described situation without ip ?
thanks

**Comment by joejulian** [comment]
The last example on https://libvirt.org/formatnetwork.html shows a network with no forward_mode and no address.

When you create a veryisolated network, https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/templates/private_network.xml.erb#L13-L28 produced a very similar network to that example with no forward mode and no ip.

**Comment by pronix** [comment]
as i understand - it should be optional ?

**Comment by joejulian** [comment]
I don't think so. It appears that forward_mode "veryisolated" differs from "none" in that the host does not have an address assigned.

**Comment by R2ZER0** [comment]
I too am facing this issue, trying to create a veryisolated network without a gateway address. 
I agree with joejulian that this should be the behavior of veryisolated - but we should probably make it backwards-compatible with people using the existing setup.
Perhaps add an options to:
 * Override matching of networks to use the name instead of IP subnet - :libvirt__match_by_name => true (default false)
 * Enable/disable a gateway address - :libirt__enable_gateway => false  (default true)

Then this would give us the desired behaviour in a flexible way. What do you think?
In my own fork ( https://github.com/R2ZER0/vagrant-libvirt/commit/f0904941994403f04c40fb09f3dd29b1fa88d371 ) i implemented this behavior without the options just to get it working, though i'm sure it can be done it a less drastic way than i have!

**Comment by joejulian** [comment]
I'm going to close this PR for now as I've found a problem still exists with tearing down the network.

I'll also put together a proper issue that explains the problem so the solution can be more clearly understood.

**Comment by R2ZER0** [comment]
Hi @joejulian,

So I am testing your latest commit ( https://github.com/joejulian/vagrant-libvirt/commit/9b7c9def3c54b75653346532ded9c5aece96ad33 ), and am trying to create a network with two VMs with :auto_config *enabled*, but am getting the error:
http://pastebin.com/raw.php?i=88pBRBWc

Here is the Vagrantfile that was used: http://pastebin.com/FfSUvCJR

Not sure what's going on there?

Thanks

**Comment by joejulian** [comment]
Thanks @R2ZER0. Fixed.

**Pull request merged**
