### PR TITLE
Add a forwarded_ports capability

### PR DESCRIPTION
**Pull request by bexelbie**
This reports the forwarded_ports in use by the VM

### CODE REVIEW

**Comment by pronix** [comment]
is it implemented in fog ?

**Comment by bexelbie** [comment]
@pronix I honestly do not know.  I am new to vagrant and libvirt.  I needed this for parity with a virtualbox image.  Can you point me toward fog and I am happy to look?

**Comment by pronix** [comment]
this patch working for you ?

**Comment by bexelbie** [comment]
I tested it using a plugin I am working on and it returned the values as expected.

**Comment by pronix** [comment]
ports are forwarded ?

**Comment by bexelbie** [comment]
All this does is allow the forwarded_ports capability to be used to report what ports are forwarded .. port forwarding was already working

**Comment by bexelbie** [comment]
This is similar to a cap provided by virtualbox

**Comment by pronix** [comment]
I not understand what doing your patch.
add description to readme, please

**Comment by electrofelix** [comment]
I believe the idea is to allow other plugins to query which ports have been forwarded based on checking the provider capabilities first to see if it can provide this information to do something with them, rather than checking if the provider is libvirt do x, virtualbox do y, docker do z, etc.

**Comment by bexelbie** [comment]
@electrofelix has the correct answer.  However, I have discovered a bug in my patch and am going to be traveling for a few days.  So please give me some time to rework it.

**Pull request closed without merging**
